language: rust

git:
  depth: false

dist: xenial
sudo: required

cache:
  cargo: true
  timeout: 240
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target

before_cache:
  - rm -rf $TRAVIS_BUILD_DIR/target/tmp

rust:
  - stable

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - wget

env:
  global:
    - RUST_BACKTRACE="1"
    - RUST_FLAGS="-C debug-assertions"

matrix:
  include:
    - os: linux
      env: TEST_SUITE=cuckoo-miner
    - os: linux
      env: TEST_SUITE=release
    - os: osx
      env: TEST_SUITE=release

# install CUDA 10 on ubuntu 16.04 via DEB from directions here 
# https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1604&target_type=debnetwork

script:
  - wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_10.0.130-1_amd64.deb
  - sudo dpkg -i cuda-repo-ubuntu1604_10.0.130-1_amd64.deb
  - sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
  - sudo apt-get update
  - sudo apt-get install cuda
  - IFS=',' read -r -a DIRS <<< "$TEST_SUITE"; DIR=${DIRS[0]};
    echo "start testing on folder $DIR...";
    if [[ -n "$DIR" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$DIR" != "release" ]];  then cd $DIR && cargo test --release && cd - > /dev/null; fi;
  - IFS=',' read -r -a DIRS <<< "$TEST_SUITE"; DIR=${DIRS[1]};
    if [[ -n "$DIR" ]];  then
      echo "start testing on folder $DIR...";
      cd $DIR && cargo test --release && cd - > /dev/null;
    fi;
  - IFS=',' read -r -a DIRS <<< "$TEST_SUITE"; DIR=${DIRS[2]};
    if [[ -n "$DIR" ]];  then
      echo "start testing on folder $DIR...";
      cd $DIR && cargo test --release && cd - > /dev/null;
    fi;

# NB, we won't be able to build cuckatoo 31 + CUDA plugins until travis supports
# ubuntu bionic beaver (18.04), which contains CUDA 10
# For now, we need to use xenial (16.04) which uses CUDA 7.5, sufficient to build
# cuckaroo29 using sm_35 architecture

before_deploy:
  - if [[ "$TEST_SUITE" == "release" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sed -i.bak 's/cuckoo_miner =/#cuckoo_miner =/g; s/##cuckoo_miner/cuckoo_miner/g' Cargo.toml;
      cargo clean; SKIP_CUCKATOO_GPU=1 cargo build --release --features opencl && ./.auto-release.sh;
    fi
  - if [[ "$TEST_SUITE" == "release" ]] && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      cargo clean; cargo build --release; ./.auto-release.sh;
    fi

deploy:
  provider: releases
  api-key:
    secure: hyoP1dOINIFF4LoVF3zh52tLg3GmKzj1urFU4o91dhB4XZazOqI5vqlMWUzmT+/fAxT+3Vf7L4Lh41BGqIGjKPOB/UQvo3PimGv2Aaz13faEyAR4HSI/NNZIx6NvAnYALy9f9pzo7D0xbfaXlIEdv4p0/KeE2RkOyRrP/twmlaLMWGKGmkHb8+TJUuDitE4A1WcnDFS9krNyNcYJeFgJJvqkw5EnPKZQrRey3LBMxQh/1PxeWgvJQBJpSFVeE+Hys5LFTcjEcnVTubjagYICw0Hslu1WYQVpP2ruolEodWOOcWU/lnKZ9X9dydZJuu1VRi/eteA73qntiRwSXz0gJlnq4MLuQl8aaDc5JZ1zvFk8jIflc44CX0fKaLakH0HlXdPBSFs9cFM4rw+5DHWc3QinrfV10EXxekybRPcwOQ2yVQObNIq+TBGoXENyY6HXNb9p4yhSdxygG72k9Nrxx79t8AFKjpbEhYgSvcFqPKv+5Y9n1fLNM1RiaKoPcUBVdkyaIDvck6ja2tu02UVTYdeIXQ53dewWEr8dGZiQMGtE23/+YppfZavxBjSiZ6QTnm1UdVjqkRIPohYbsBh9vydAtr6Ufx4GvBf6r3U2LkuaL2s/NbJsEO9JTeSjOH3zTOJdR90+lTSKUKXYAGC5i3qvRfVWFefjxqWv0nyLTrs=
  file_glob: true
  file: deploy/grin-miner-*.tgz*
  skip_cleanup: true
  on:
    repo: mimblewimble/grin-miner
    tags: true
